export const SUPABASE_CLIENT = Symbol('SUPABASE_CLIENT');
export const SUPABASE_PUBLIC_BUCKET = Symbol('SUPABASE_PUBLIC_BUCKET');
export const SUPABASE_PRIVATE_BUCKET = Symbol('SUPABASE_PRIVATE_BUCKET');
