export const LOCAL_STORAGE_BASE_PATH = Symbol('LOCAL_STORAGE_BASE_PATH');
export const LOCAL_STORAGE_PUBLIC_BASE_URL = Symbol('LOCAL_STORAGE_PUBLIC_BASE_URL');
export const LOCAL_STORAGE_SIGNING_SECRET = Symbol('LOCAL_STORAGE_SIGNING_SECRET');
