export const STORAGE_PROVIDER = Symbol('STORAGE_PROVIDER');
export const STORAGE_CONFIG = Symbol('STORAGE_CONFIG');
export const STORAGE_VALIDATORS = Symbol('STORAGE_VALIDATORS');
export const STORAGE_IMAGE_PROCESSOR = Symbol('STORAGE_IMAGE_PROCESSOR');
